### ISSUE TITLE
Bug Photino.Native DllNotFoundException

### ISSUE THREAD

**Issue by evnpresson** [sql-bi/Bravo#258]
Hello,

I use an Azure Remote Desktop to run Power BI Desktop. I have installed Bravo on my remote desktop but I receive the following error when I try to run it:

System.DllNotFoundException: Unable to load DLL 'Photino.Native' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at PhotinoNET.PhotinoWindow.Photino_register_win32(IntPtr hInstance)
   at PhotinoNET.PhotinoWindow.<>c.<.ctor>b__238_0()
   at PhotinoNET.PhotinoWindow.Invoke(Action workItem)
   at PhotinoNET.PhotinoWindow..ctor(PhotinoWindow parent)
   at Sqlbi.Bravo.Infrastructure.AppWindow.CreateWindow() in D:\a\1\s\src\Infrastructure\AppWindow.cs:line 58
   at Sqlbi.Bravo.Infrastructure.AppWindow..ctor(IHost host, AppInstance instance) in D:\a\1\s\src\Infrastructure\AppWindow.cs:line 35
   at Sqlbi.Bravo.Program.Main() in D:\a\1\s\src\Program.cs:line 25

**Comment by danieleperilli** [comment]
Duplicate of #225

**Comment by albertospelta** [comment]
Hi @evnpresson, please see my response to https://github.com/sql-bi/Bravo/issues/225#issuecomment-1083064111 as the same applies here.
