### ISSUE TITLE
Minimum requirements for the installation of Bravo

### ISSUE THREAD

**Issue by jafernandezpuga** [sql-bi/Bravo#282]
### The feature request

Hello everyone,
Is it a minimum requirement to have Windows 10 to install Bravo for Power BI?
I am currently installing it on Windows 8.1 and I am getting the following error:

```
System.DllNotFoundException: Unable to load DLL 'Photino.Native' or one of its dependencies: No se encontró el proceso especificado. (0x8007007F)
at PhotinoNET.PhotinoWindow.Photino_register_win32(IntPtr hInstance)
at PhotinoNET.PhotinoWindow.<>c.<.ctor>b__238_0()
at PhotinoNET.PhotinoWindow.Invoke(Action workItem)
at PhotinoNET.PhotinoWindow..ctor(PhotinoWindow parent)
at Sqlbi.Bravo.Infrastructure.AppWindow.CreateWindow() in D:\a\1\s\src\Infrastructure\AppWindow.cs:line 58
at Sqlbi.Bravo.Infrastructure.AppWindow..ctor(IHost host, AppInstance instance) in D:\a\1\s\src\Infrastructure\AppWindow.cs:line 35
at Sqlbi.Bravo.Program.Main() in D:\a\1\s\src\Program.cs:line 25
```

I have installed the Microsoft Visual C++ runtime libraries and I am getting the following error:

`The GetdpiforWindow procedure entry point cannot be found in the dynamic link library C:\Program Files\SQLBI\Bravo\'Photino.Native.dll`

Regards

### Proposed solution

Show what are the minimum requirements for installing Bravo for Power BI.

**Comment by albertospelta** [comment]
Hi @jafernandezpuga,
The minimum supported client version is Windows 10 version 1809 build 10.0.17763 ( Windows 10 October 2018 Update )
We will add this information to the project documentation and consider whether to add a warning during installation as well.

**Comment by albertospelta** [comment]
Added in [0.9.3](https://github.com/sql-bi/Bravo/releases/tag/v0.9.3)
