### ISSUE TITLE
Automatic preview hangs indefinitely

### ISSUE THREAD

**Issue by albertospelta** [sql-bi/Bravo#433]
### Describe the problem

Format DAX measure analysis hangs indefinitely if automatic preview is enabled

### Bravo version

n/a

### Tabular model

Power BI Desktop, import mode

### Power BI

n/a

### Steps to reproduce the behavior

- Enable Options\Formatting\Automatic preview
- Connect to a PBIX model and select Format Dax

### Additional context

``` js
Uncaught TypeError: Cannot read properties of null (reading 'offsetWidth')
    at Function.elVisible (tabulator_esm.js:179:15)
    at ColumnManager.redraw (tabulator_esm.js:20770:14)
    at Tabulator.redraw (tabulator_esm.js:24909:22)
    at DaxFormatterScene.updateMeasuresStatus (scene-dax-formatter.ts:289:24)
    at DaxFormatterScene.generateFormattedPreview (scene-dax-formatter.ts:246:14)
    at DaxFormatterScene.maybeAutoGenerateFormattedPreview (scene-dax-formatter.ts:236:18)
    at DaxFormatterScene.update (scene-dax-formatter.ts:442:14)
    at DaxFormatterScene.render (scene-dax-formatter.ts:174:14)
    at Page.showScene (page.ts:94:19)
    at Page.show (page.ts:84:14)
```

**Comment by albertospelta** [comment]
Fixed in version [0.9.5](https://github.com/sql-bi/Bravo/releases/tag/v0.9.5)
