### ISSUE TITLE
HTTP/401 Unauthorized error after upgrading TOM to v19.57.2

### ISSUE THREAD

**Issue by albertospelta** [sql-bi/Bravo#603]
### Describe the problem

Updating TOM to version 19.57.2 will result in `(401) Unauthorized` error when connecting to a dataset in `My Workspace`

### Bravo version

n/a

### Tabular model

Power BI Dataset

### Power BI

n/a

### Additional context

```
[HOST] UnhandledException
Microsoft.AnalysisServices.AdomdClient.AdomdConnectionException: The remote server returned an error: (401) Unauthorized.
---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.AnalysisServices.Utilities.ConnectivityHelper.ExecuteJsonBasedHttpRequestImpl[TRequest,TResult](Uri uri, String method, IDictionary`2 headers, TRequest requestContent, JsonHttpRequestOptions options, Int32 timeout, DataContractJsonSerializer requestSeriralizer, DataContractJsonSerializer responseSerializer, Boolean getResponseHeaders, Boolean getResponseContent, HttpStatusCode& status, String& technicalDetails, WebHeaderCollection& responseHeaders)\
   at Microsoft.AnalysisServices.Utilities.ConnectivityHelper.ExecuteJsonBasedHttpPutRequest[TRequest,TResult](Uri uri, IDictionary`2 headers, TRequest requestBody, JsonHttpRequestOptions options, Int32 timeout, DataContractJsonSerializer requestSeriralizer, DataContractJsonSerializer responseSerializer, String& technicalDetails)
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ResolvePowerBICluster(Uri discoverUrl, String token, TimeLeft timeLeft, AsInstanceType asInstanceType)
   --- End of inner exception stack trace ---
   at Microsoft.AnalysisServices.AdomdClient.ASAzureUtility.ResolvePowerBICluster(Uri discoverUrl, String token, TimeLeft timeLeft, AsInstanceType asInstanceType)
   at Microsoft.AnalysisServices.AdomdClient.ConnectionInfo.ValidateAndSetPbiDatasourceAndLocation()
   at Microsoft.AnalysisServices.AdomdClient.ConnectionInfo.HandlePaaSInfrastructureConnection()
   at Microsoft.AnalysisServices.AdomdClient.ConnectionInfo.ValidateAndCompleteConnectionConfiguration()
   at Microsoft.AnalysisServices.AdomdClient.ConnectionInfo.SetConnectionString(String cs)
   at Microsoft.AnalysisServices.AdomdClient.ConnectionInfo..ctor(String connectionString)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.XmlaClientProvider.Microsoft.AnalysisServices.AdomdClient.AdomdConnection.IXmlaClientProviderEx.set_ConnectionString(String value)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection.set_ConnectionString(String value)
   at Microsoft.AnalysisServices.AdomdClient.AdomdConnection..ctor(String connectionString)
   at Sqlbi.Bravo.Infrastructure.Services.AdomdConnectionWrapper..ctor(String connectionString, String databaseName) in C:\\Users\\alberto\\source\\repos\\github\\sql-bi\\Bravo\\src\\Infrastructure\\Services\\ConnectionWrapper.cs:line 78
```

**Comment by albertospelta** [comment]
This issue seems to be solved in TOM version 19.60.0
